#!/usr/bin/env sh
name="Shyam-Has-Your-Anomaly-Mitigated";
email="shyam@shyam.id.au";
host="github.com";
repo="shyam";
address="https://$name@$host/$name/$repo.git";

# https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf
git config --global user.name "$name";
git config --global user.email "$email";
git config --global color.ui auto;
git clone "$address";
